version: "3.8"
services:
  web:
    env_file: .env.dev
    depends_on:
       - dbaa
    links:
      - dbaa
  dbaa:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dcaa
      POSTGRES_USER: postgres
    ports:
      - "5916:5432"
    volumes:
      - dcaa-postgres:/var/lib/postgresql/data-new
volumes:
  dcaa-postgres:
