use sea_orm_migration::{prelude::*, sea_orm::Statement};

use crate::utils::raw_sql_migration;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let sql = "
            INSERT INTO nations VALUES 
            (DEFAULT, NULL, 'The Fretful Ones', 0, TRUE, 'The men and women of the eastern plains aren''t much for fighting and are frightened of outsiders and foreign nations. They''re farmers on undesirable land and rarely have a need to take up arms but will defend themselves if they have to.'),

            (DEFAULT, NULL, 'Garden Pacifists', 0, TRUE, 'The garden sanctuary home to the Garden Pacifists is a tranquil, predominantly unknown territory in The Realm, and the resulting society that developed is a pacifist nation, primarily interested in cultivating beauty and nourishment in their elaborate garden towns. The citizens work to synthesize, not separate, their work in the dirt with their lifestyle and way of living. While fascinating to study from an anthropological view, they are vulnerable to any potential army that could happen to stumble upon them.'),
            
            (DEFAULT, NULL, 'Badlands Guild', 0, TRUE, 'The Badlands Guild is a haven for the nameless and lost. Travelers who have strayed from their path or those who have a past that prevents them from leading seemingly ordinary lives take refuge here. Those who come across a Guild member are more likely to find their purse a little light of coin than anything else. But don''t get them wrong; they will put a dagger in your back and twist it if the situation calls for it. In the Guild, nobody judges who you were, but you will defend your territory until death— do that, or be cast out.'),
            
            (DEFAULT, NULL, 'Wayward Marauders', 0, TRUE, 'The Wayward Marauders formed under unique circumstances: a perfect storm. A leader of a small barbarian clan fell smitten with an Amazonian chieftess with a following. The results would lead to the beginnings of a new clan, thus resulting in the Wayward Marauders. This bizarre union happened long ago, but today, the clan continues to thrive. While they''re not known for diplomacy or building cities, they are somewhat capable on the battlefield.'),
            
            (DEFAULT, NULL, 'Dire Canyon', 0, TRUE, 'Those who seek refuge in the Dire Canyon are generally peaceful beings, but they are very capable of defending themselves when needed. A few centuries ago, a group of nomadic mercenaries was traveling the Great White Desert in search of an ancient treasure that had eluded humankind forever. They would never find that which they set out for, but they would ultimately build a civilization in the Red Chasm— calling it Dire Canyon.'),
            
            (DEFAULT, NULL, 'Merchants of the Narrows', 0, TRUE, 'The Merchants of the Narrows reside in a labyrinth of narrow canals and marketplaces built atop precarious stilts and platforms that seemingly defy the laws of balance. They are shrewd negotiators, navigating the intricate waterways of their homeland with the same skills they use to barter trade deals. While they prefer commerce to conflict, their wealth and influence make them a tempting target for rivals or those trying to get rich quickly. Despite their focus on profit, they are not afraid to defend their interests fiercely when threatened, turning their intricate marketplaces into impromptu battlegrounds if need be.'),
            
            (DEFAULT, NULL, 'Alpha Union', 0, TRUE, 'The Highborn Cavalry, descendants of noble lineage, are master equestrians who have honed their skills on the battlefield for generations. Mounted on mighty steeds and clad in gleaming armor, they epitomize the pinnacle of martial prowess and chivalry. The Avian Cliff Dwellers, on the other hand, soar above the fray, their wings carrying them effortlessly through the skies. Born amidst the rugged peaks and perilous cliffs of their ancestral homeland, they have adapted to life in the clouds with unmatched agility and cunning. Together, these two clans form the backbone of the Alpha Union.'),
            
            (DEFAULT, NULL, 'Beta Vigilantes', 0, TRUE, 'The Beta Vigilantes are a shadowy organization that operates outside the confines of traditional law and order. Comprised of outcasts, renegades, and disillusioned former law enforcement officers, they see themselves as the last line of defense against corruption and injustice. Operating from hidden bases and safehouses scattered throughout the land, they strike swiftly and decisively against those they deem to be a threat to the common good. While their methods may be unorthodox and their motives murky, they are driven by a fierce sense of justice and a determination to right the wrongs of the world, even if it means crossing moral boundaries in the process.'),
            
            (DEFAULT, NULL, 'Commune of Gamma', 0, TRUE, 'Within the Commune of Gamma, a diverse trio of clans thrive, woven with the enigmatic presence of the Magi Enforcers, the ominous aura of the Skull Clan Death Cultists, and the untamed vigor of the Barbarians of the Outer Steppe. Despite their stark differences, they are bound by a shared determination to safeguard their homeland so that they all have a place where they can practice their arts away from unapproving and prying eyes.'),
            
            (DEFAULT, NULL, 'Delta City', 0, TRUE, 'Delta City was one of the original settlements dating back to the century of creation. Initially, it was a hub, simply known as Delta, where three rivers converged. Early settlers in Delta quickly began manipulating the land, building a stone city above the Azure, Snake, and Emerald rivers. With an intricate combination of bridges and aqueducts, Delta City was born. Today, the city is very diverse and a very wellknown stop to anyone who''s ever traversed through the Delta Region.'),
            
            (DEFAULT, NULL, 'Epsilon Rough Necks', 0, TRUE, 'In the rugged wilderness of Epsilon, where the earth is scarred by ancient battles and the sky echoes with the howls of distant beasts, the Rough Necks carve out their existence. Born from the crucible of hardship and survival, they are a band of hardened warriors and wilderness dwellers, bound by a fierce loyalty to each other and the untamed land they call home. Their camps dot the landscape like scattered wildflowers, hidden among the rocky crags and dense forests that encapsulate their domain. From these remote outposts, they roam the wilds, hunting formidable prey and defending their territory with unmatched ferocity.'),
            
            (DEFAULT, NULL, 'Zeta Realm', 0, TRUE, 'In the heart of the vast and storied Zeta Realm, a sizeable chunk of land is shared by various cultures that have unified under a solitary banner. Here, the Imperial Legionnaires stand as the stalwart guardians of order and sovereignty. Along the northern borders, the North Watch Longbowmen keep a vigilant eye, and circling the perimeter are the Oath-Sworn Knights, with their gleaming armor and noble steeds. And finally, to the south, amidst the ancient woodlands, the Elven Archers live among the trees. Together, these noble warriors form the backbone of the Zeta Realm.'),
            
            (DEFAULT, NULL, 'Warriors of Eta', 0, TRUE, 'In the shadowed valleys of the Eta Mountains, where the peaks pierce the sky like razor-sharp spears of obsidian, the Warriors of Eta reside. As legend has it, the founder of Eta was born from the bloodline of dragons and the spirits of the earth. This bolstered their belief that the original settlers were masters of elemental magic and martial prowess. Clad in armor forged from enchanted metals found within the valley and wielding weapons imbued with the power of the elements, they channel the fury of their ancestral lands to ward away any threats.'),
            
            (DEFAULT, NULL, 'Theta Troopers', 0, TRUE, 'Across the windswept plains of the Theta Wastelands, where storms rage and lightning dances across the sky, the Theta Troopers established a sizeable settlement to call their own. Originally comprised of retired soldiers who were too old to by the standards set by some kings, they yet proved to be more than capable on the battlefield. However, they weren''t known to be violent in any regard, but to anyone looking for vengeance with a purse of coin, they''d be more than happy to do the devil''s work.'),
            
            (DEFAULT, NULL, 'Coastal Clan Iota', 0, TRUE, 'The Coastal Clan has been a well-known, and also well-avoided area on the Northeastern coast. Originally erected by a band of archers and a group of Ronin Immortals, the numbers mystically grew over the years, leading to a sizeable clan settlement. With their backs to the sea and plenty of resources, those who arrive at the gates better have something worth trading, or it''ll be their life they end up bartering for. It''s this cutthroat mentality that provokes most weary travelers to steer clear. However, to those who have the coin or prove to be useful they may just find themselves able to seek refuge with the CCI.'),
            
            (DEFAULT, NULL, 'Kappa Society', 0, TRUE, 'The Kappa Society emerged from the ashes of a once-divided land, where warring clans finally united under a single banner in the face of a common enemy. They are a society forged in the crucible of conflict, their strength born from the unity of diverse peoples and cultures. Each member of the faction is trained from birth to embody the virtues of discipline, loyalty, and courage, forming a formidable military force that strikes fear into the hearts of their adversaries. However, beneath their unwavering facade of unity lies a web of political intrigue and power struggles as different factions vie for dominance within the Society''s hierarchy.'),
            
            (DEFAULT, NULL, 'Lambda Vanguard', 0, TRUE, 'In the celestial expanse of the Etherial Realms, where stars are but distant beacons in an endless sea of magic, the Lambda Vanguard emerges as custodians of arcane knowledge and guardians of the Astral Gates. Perched high above the Lambda Peaks, the Vanguard is composed of mystic sages, ethereal monks, celestial knights, as well as others. Armed with ancient spells and enchanted relics, they stand resolute against the encroaching darkness, their journey through the realms guided by a quest for enlightenment and the preservation of cosmic harmony.'),
            
            (DEFAULT, NULL, 'Dominion of Mu', 0, TRUE, 'Beyond the sea of the Great Abyss lies a vibrant forest older than time itself. It''s these woodlands that make up the homeland for the Dominion of Mu—a realm forged from the unity of disparate archer clans. Once locked in an endless cycle of rivalry and conflict, the clans finally came together under the banner of a new generation of monarchs. Guided by the wisdom of their rulers and the bonds of a shared heritage, the Dominion of Mu now works as one to protect their realm from the encroachment of outsiders and those keen on stealing their land.'),
            
            (DEFAULT, NULL, 'Nu Republic', 0, TRUE, 'The origins of the Nu Republic are entirely an interesting one. Over a century ago, a group of kings purchased contracts with various mercenary groups and instructed them to attack their enemies in Nu-Land. At the hands of these skilled mercenaries, the task was but a simple one, however, the kings would ultimately lose the war and not be able to pay off the second half of their contracts. This led to the mercenaries taking the recently claimed land as their own and forming what is now known as the Nu Republic.'),
            
            (DEFAULT, NULL, 'Xi Tribe', 0, TRUE, 'Amidst the untamed wilderness of the Xi Wastelands, where the earth is scorched by relentless sun and the winds howl with the fury of the desert, the Xi Tribe roams as nomads of the sands. Descendants of ancient warriors and mystics, they have mastered the harsh landscape through a combination of survival instincts and spiritual wisdom. Clad in desert robes and adorned with tribal markings, they move with the grace of desert foxes and the strength of desert lions, guarding their ancestral lands with fierce determination and unwavering loyalty to their traditions.'),
            
            (DEFAULT, NULL, 'Omicron Quadrant', 0, TRUE, 'The Omicron Quadrant was initially a large expanse of land that belonged to various tribes. As time lurched forward, these tribes expanded, and before they knew it, they found themselves at each other''s borders. In a time of war and death, the common thing would have been for these groups to battle one another for supremacy and control of the land. Still, the nobles of the tribes had a meeting of the minds and believed it to be more beneficial to work together and become one nation. That nation was the Omicron Quadrant.'),
            
            (DEFAULT, NULL, 'Principality of Pi', 0, TRUE, 'Out in the far reaches of the western mountains lies a series of temples erected atop the rocky cliffs called the Principality of Pi. Comprised of monks and Shinobi martial artists, their dedication to their craft goes relatively unmatched. Capable of spending months in meditation, the soldiers that defend the Principality hold a higher pain tolerance than most, making them capable of extraordinary feats. While peace is of the utmost importance, they are more than willing to eradicate anyone who stands in the way of it.'),
            
            (DEFAULT, NULL, 'Gates of Rho', 0, TRUE, 'The Gates of Rho once stood as the first line of defense for the mighty Kingdom of Rho. For centuries, the King ruled the land with an iron fist, and while attacked multiple times, none of his enemies were ever able to get past the Gates of Rho. Towering and foreboding as they were, it was some arrant words that caught the general''s ear spoken by the King. This led to a falling out, and the King and his castle fell. Left in its wake was a new nation, one that goes simply by The Gates of Rho.'),
            
            (DEFAULT, NULL, 'Matriarchy of Sigma', 0, TRUE, 'Across the land, the gender of a soldier means little in regard to who can fight for their homeland. Even so, there are many rulers who don''t share this way of thinking and believe that on the battlefield, nothing is stronger than man. The Matriarchy of Sigma stands solely against that outlook and is led predominantly by female warriors, archers, magi, and others. At the same time, they do have men among their ranks; however, it''s clear who runs the show in the Matriarchy.'),
            
            (DEFAULT, NULL, 'Land of Tau', 0, TRUE, 'The Land of Tau is a vast and mystical forest that belongs to two primary groups: a band of Elven archers and a small tribe of Amazonians. Both were cast from their homelands for similar reasons; their paths crossed in the most enigmatic landscapes. Instantly encapsulated by one another, the two groups created a settlement and started training vigorously, just in case those who cast them out came to destroy them. It was their immense training that led to them becoming an extremely formidable opponent to anyone on the battlefield.'),
            
            (DEFAULT, NULL, 'Upsilon Realm', 0, TRUE, 'The Upsilon Realm is one of the oldest standing alliances, making it one of the most well-known. For young kids and aspiring adults, the Upsilon Realm is something of a house of heroes, their stories finding their way to taverns and books across the land. Everyone with a penchant for do-gooding or vigilantism, at one point or another, finds themselves idolizing those lucky enough to take up ranks in Upsilon. Standing as a beacon of hope and sentinel for all that is good, the warriors of Upsilon don''t falter in dangerous situations, and anyone in need should feel relieved if these champions show up in their favor.'),
            
            (DEFAULT, NULL, 'Cult of Phi', 0, TRUE, 'The Bubonic Swamp, in the deepest southern void, is home to the evil organization that calls itself the Cult of Phi. To many, they don''t exist, the name simply serving as a means of scaring children away from the swamps at night, but the elders knew the truth. Those stories were born from missing children claims throughout the centuries. As it turns out, when the Cult needs to bolster their numbers, they''ll journey out from their homeland and snatch up unsuspecting youths in order to train them for their own nefarious needs.'),
            
            (DEFAULT, NULL, 'Sovereignty of Chi', 0, TRUE, 'It goes without saying that monks and death cultists generally don''t mix, but in the case of the Sovereignty of Chi, that couldn''t be further from the truth. These tribes, both fighting separate wars unbeknownst to each other, found themselves backed into an uninhabited area of the hazy marshland. Fearing to be too weak on their own, they joined forces and successfully thwarted both their enemies. This sharing of blood created a bond between them, and thus, the Sovereignty of Chi was born— forever in one another''s debt.'),
            
            (DEFAULT, NULL, 'Psi Empire', 0, TRUE, 'Magic is a powerful ability to wield, and those in the Psi Empire take full advantage of it. Despite being a relatively small civilization, they easily make up for any shortcomings with their immense understanding of the arcane arts. Mainly comprised of magic-oriented soldiers, the knights of the realm are heavily enchanted, making them among the most feared entities to don Oath-Sworn armor. They say Rome wasn''t built in a day, but the Psi Empire was— and over a thousand years later, it still stands as a force to be reckoned with.'),
            
            (DEFAULT, NULL, 'Omega Dominion Elite', 0, TRUE, 'The Omega Dominion Elites are the most feared faction in the entire land. Their numbers are uncountable, and the experience and diversity of their army are unlike any that have ever been fathomed. At the same time, they''re nowhere close to the largest settlement or kingdom in the land; even the most prominent rulers fear them. The ODE is capable of erecting a battle camp in mere minutes, successfully creating a temporary home wherever they''re needed.')
        ";
        let statement = Statement::from_string(manager.get_database_backend(), sql.to_owned());
        raw_sql_migration(manager, statement).await
    }
}
