//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "aoe_spread")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub spread: i32,
    #[sea_orm(column_type = "Decimal(Some((2, 1)))")]
    pub aoe: Decimal,
    pub hits: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
