//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3
#![allow(warnings)]
pub mod prelude;

pub mod armies;
pub mod battles;
pub mod campaign_levels;
pub mod nation_armies;
pub mod nations;
pub mod users;
