//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub auth0_sub: String,
    pub email: String,
    pub email_verified: bool,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::nations::Entity")]
    Nations,
}

impl Related<super::nations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
