//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "weapon_armor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub weapon: String,
    pub armor: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub reduction: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
